[simulation]
dt = 0.001
total_time = 5.0
integrator = "runge_kutta4"

[bodies.body1]
mass = 2.5
inertia = [1.0, 0.0, 0.0,
           0.0, 1.0, 0.0,
           0.0, 0.0, 1.0]
initial_position = [0.0, 1.0, 0.0]
initial_velocity = [2.0, 0.0, 0.0]

[constraints.joint1]
type = "revolute"
body_a = "body1"
body_b = "body2"
anchor_point = [0.0, 0.5, 0.0]
axis = [1.0, 0.0, 0.0]